# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Update.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(640, 480)
        self.textEdit_Senior = QtGui.QTextEdit(Dialog)
        self.textEdit_Senior.setGeometry(QtCore.QRect(470, 320, 161, 101))
        self.textEdit_Senior.setObjectName(_fromUtf8("textEdit_Senior"))
        self.label_Phone = QtGui.QLabel(Dialog)
        self.label_Phone.setGeometry(QtCore.QRect(210, 260, 61, 21))
        self.label_Phone.setFrameShape(QtGui.QFrame.Box)
        self.label_Phone.setFrameShadow(QtGui.QFrame.Plain)
        self.label_Phone.setLineWidth(2)
        self.label_Phone.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Phone.setObjectName(_fromUtf8("label_Phone"))
        self.label_Grade = QtGui.QLabel(Dialog)
        self.label_Grade.setGeometry(QtCore.QRect(210, 110, 61, 21))
        self.label_Grade.setFrameShape(QtGui.QFrame.Box)
        self.label_Grade.setFrameShadow(QtGui.QFrame.Plain)
        self.label_Grade.setLineWidth(2)
        self.label_Grade.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Grade.setObjectName(_fromUtf8("label_Grade"))
        self.lineEdit = QtGui.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(280, 80, 113, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label_Level = QtGui.QLabel(Dialog)
        self.label_Level.setGeometry(QtCore.QRect(10, 50, 51, 21))
        self.label_Level.setFrameShape(QtGui.QFrame.Box)
        self.label_Level.setFrameShadow(QtGui.QFrame.Plain)
        self.label_Level.setLineWidth(2)
        self.label_Level.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Level.setObjectName(_fromUtf8("label_Level"))
        self.label_Phone_2 = QtGui.QLabel(Dialog)
        self.label_Phone_2.setGeometry(QtCore.QRect(210, 290, 61, 21))
        self.label_Phone_2.setFrameShape(QtGui.QFrame.Box)
        self.label_Phone_2.setFrameShadow(QtGui.QFrame.Plain)
        self.label_Phone_2.setLineWidth(2)
        self.label_Phone_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Phone_2.setObjectName(_fromUtf8("label_Phone_2"))
        self.Btn_Cancel = QtGui.QPushButton(Dialog)
        self.Btn_Cancel.setGeometry(QtCore.QRect(560, 440, 75, 31))
        self.Btn_Cancel.setObjectName(_fromUtf8("Btn_Cancel"))
        self.label_Freshman = QtGui.QLabel(Dialog)
        self.label_Freshman.setGeometry(QtCore.QRect(400, 80, 61, 21))
        self.label_Freshman.setFrameShape(QtGui.QFrame.Box)
        self.label_Freshman.setFrameShadow(QtGui.QFrame.Plain)
        self.label_Freshman.setLineWidth(2)
        self.label_Freshman.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Freshman.setObjectName(_fromUtf8("label_Freshman"))
        self.lineEdit_7 = QtGui.QLineEdit(Dialog)
        self.lineEdit_7.setGeometry(QtCore.QRect(280, 260, 113, 20))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.label_Junior = QtGui.QLabel(Dialog)
        self.label_Junior.setGeometry(QtCore.QRect(400, 200, 61, 21))
        self.label_Junior.setFrameShape(QtGui.QFrame.Box)
        self.label_Junior.setFrameShadow(QtGui.QFrame.Plain)
        self.label_Junior.setLineWidth(2)
        self.label_Junior.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Junior.setObjectName(_fromUtf8("label_Junior"))
        self.Btn_Check = QtGui.QPushButton(Dialog)
        self.Btn_Check.setGeometry(QtCore.QRect(480, 440, 75, 31))
        self.Btn_Check.setObjectName(_fromUtf8("Btn_Check"))
        self.Btn_Grade = QtGui.QPushButton(Dialog)
        self.Btn_Grade.setGeometry(QtCore.QRect(170, 10, 75, 31))
        self.Btn_Grade.setObjectName(_fromUtf8("Btn_Grade"))
        self.label_Number = QtGui.QLabel(Dialog)
        self.label_Number.setGeometry(QtCore.QRect(210, 80, 61, 21))
        self.label_Number.setFrameShape(QtGui.QFrame.Box)
        self.label_Number.setFrameShadow(QtGui.QFrame.Plain)
        self.label_Number.setLineWidth(2)
        self.label_Number.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Number.setObjectName(_fromUtf8("label_Number"))
        self.label_Major = QtGui.QLabel(Dialog)
        self.label_Major.setGeometry(QtCore.QRect(210, 170, 61, 21))
        self.label_Major.setFrameShape(QtGui.QFrame.Box)
        self.label_Major.setFrameShadow(QtGui.QFrame.Plain)
        self.label_Major.setLineWidth(2)
        self.label_Major.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Major.setObjectName(_fromUtf8("label_Major"))
        self.lineEdit_5 = QtGui.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(280, 200, 113, 20))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.label_Class = QtGui.QLabel(Dialog)
        self.label_Class.setGeometry(QtCore.QRect(110, 50, 51, 21))
        self.label_Class.setFrameShape(QtGui.QFrame.Box)
        self.label_Class.setFrameShadow(QtGui.QFrame.Plain)
        self.label_Class.setLineWidth(2)
        self.label_Class.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Class.setObjectName(_fromUtf8("label_Class"))
        self.lineEdit_4 = QtGui.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(280, 170, 113, 20))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.label_Title_2 = QtGui.QLabel(Dialog)
        self.label_Title_2.setGeometry(QtCore.QRect(210, 440, 261, 31))
        self.label_Title_2.setFrameShape(QtGui.QFrame.Box)
        self.label_Title_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_Title_2.setLineWidth(1)
        self.label_Title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Title_2.setObjectName(_fromUtf8("label_Title_2"))
        self.lineEdit_3 = QtGui.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(280, 140, 113, 20))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.textEdit_Freshman = QtGui.QTextEdit(Dialog)
        self.textEdit_Freshman.setGeometry(QtCore.QRect(470, 80, 161, 101))
        self.textEdit_Freshman.setObjectName(_fromUtf8("textEdit_Freshman"))
        self.tableView = QtGui.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(10, 80, 191, 391))
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.comboBox_2 = QtGui.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(170, 50, 31, 22))
        self.comboBox_2.setMaxVisibleItems(3)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.label_Name = QtGui.QLabel(Dialog)
        self.label_Name.setGeometry(QtCore.QRect(210, 200, 61, 21))
        self.label_Name.setFrameShape(QtGui.QFrame.Box)
        self.label_Name.setFrameShadow(QtGui.QFrame.Plain)
        self.label_Name.setLineWidth(2)
        self.label_Name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Name.setObjectName(_fromUtf8("label_Name"))
        self.textEdit_Junior = QtGui.QTextEdit(Dialog)
        self.textEdit_Junior.setGeometry(QtCore.QRect(470, 200, 161, 101))
        self.textEdit_Junior.setObjectName(_fromUtf8("textEdit_Junior"))
        self.label_Senior = QtGui.QLabel(Dialog)
        self.label_Senior.setGeometry(QtCore.QRect(400, 320, 61, 21))
        self.label_Senior.setFrameShape(QtGui.QFrame.Box)
        self.label_Senior.setFrameShadow(QtGui.QFrame.Plain)
        self.label_Senior.setLineWidth(2)
        self.label_Senior.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Senior.setObjectName(_fromUtf8("label_Senior"))
        self.label_Group = QtGui.QLabel(Dialog)
        self.label_Group.setGeometry(QtCore.QRect(210, 140, 61, 21))
        self.label_Group.setFrameShape(QtGui.QFrame.Box)
        self.label_Group.setFrameShadow(QtGui.QFrame.Plain)
        self.label_Group.setLineWidth(2)
        self.label_Group.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Group.setObjectName(_fromUtf8("label_Group"))
        self.lineEdit_2 = QtGui.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(280, 110, 113, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.textEdit_Voluntary = QtGui.QTextEdit(Dialog)
        self.textEdit_Voluntary.setGeometry(QtCore.QRect(280, 290, 111, 131))
        self.textEdit_Voluntary.setObjectName(_fromUtf8("textEdit_Voluntary"))
        self.lineEdit_6 = QtGui.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(280, 230, 113, 20))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.comboBox = QtGui.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(70, 50, 31, 22))
        self.comboBox.setMaxVisibleItems(3)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.Btn_Update = QtGui.QPushButton(Dialog)
        self.Btn_Update.setGeometry(QtCore.QRect(90, 10, 75, 31))
        self.Btn_Update.setObjectName(_fromUtf8("Btn_Update"))
        self.Btn_studentInf = QtGui.QPushButton(Dialog)
        self.Btn_studentInf.setGeometry(QtCore.QRect(10, 10, 75, 31))
        self.Btn_studentInf.setObjectName(_fromUtf8("Btn_studentInf"))
        self.label_Title = QtGui.QLabel(Dialog)
        self.label_Title.setGeometry(QtCore.QRect(210, 50, 421, 21))
        self.label_Title.setFrameShape(QtGui.QFrame.Box)
        self.label_Title.setFrameShadow(QtGui.QFrame.Plain)
        self.label_Title.setLineWidth(2)
        self.label_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Title.setObjectName(_fromUtf8("label_Title"))
        self.label_Address = QtGui.QLabel(Dialog)
        self.label_Address.setGeometry(QtCore.QRect(210, 230, 61, 21))
        self.label_Address.setFrameShape(QtGui.QFrame.Box)
        self.label_Address.setFrameShadow(QtGui.QFrame.Plain)
        self.label_Address.setLineWidth(2)
        self.label_Address.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Address.setObjectName(_fromUtf8("label_Address"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_Phone.setText(_translate("Dialog", "Phone", None))
        self.label_Grade.setText(_translate("Dialog", "Grade", None))
        self.label_Level.setText(_translate("Dialog", "Level", None))
        self.label_Phone_2.setText(_translate("Dialog", "Voluntary", None))
        self.Btn_Cancel.setText(_translate("Dialog", "Cancel", None))
        self.label_Freshman.setText(_translate("Dialog", "Freshman", None))
        self.label_Junior.setText(_translate("Dialog", "Junior", None))
        self.Btn_Check.setText(_translate("Dialog", "Check", None))
        self.Btn_Grade.setText(_translate("Dialog", "Grade", None))
        self.label_Number.setText(_translate("Dialog", "Number", None))
        self.label_Major.setText(_translate("Dialog", "Major", None))
        self.label_Class.setText(_translate("Dialog", "Class", None))
        self.label_Title_2.setText(_translate("Dialog", "Student Information System", None))
        self.label_Name.setText(_translate("Dialog", "Name", None))
        self.label_Senior.setText(_translate("Dialog", "Senior", None))
        self.label_Group.setText(_translate("Dialog", "Group", None))
        self.Btn_Update.setText(_translate("Dialog", "Update", None))
        self.Btn_studentInf.setText(_translate("Dialog", "Student Inf", None))
        self.label_Title.setText(_translate("Dialog", "Student Information Selected", None))
        self.label_Address.setText(_translate("Dialog", "Address", None))

